[package]
name = "autorelease"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
gix = { version = "0.56.0", features = ["revision"] }
semver = "1.0.20"
